### ISSUE TITLE
Remove/Improve Gmail access

### ISSUE THREAD

**Issue by Jester182uk** [LombardiDaniel/ip-checker#1]
Is it possible to remove/improve the Gmail login as they are depreciating less secure apps accesses of 30 May 2022. [Less secure apps & your Google Account](https://support.google.com/accounts/answer/6010255?hl=en)

**Comment by LombardiDaniel** [comment]
Thanks for the feedback! I'll take a look into it this week and update it asap!

**Comment by LombardiDaniel** [comment]
@Jester182uk I have removed the Gmail login. Now you will only be notified via telegram. As a note, you may need to update `libseccomp2 ` to `libseccomp2/stable,now 2.5.1-1+rpi1+deb11u1 armhf` in order for docker correctly build the image.
